name: 'JSON to variables'
author: 'Roberto García'
description: 'This action reads json file and writes its content as environment variables'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  filename: 
    description: 'The json file.'
    required: true
  prefix:
    description: 'The prefix for variables.'
    required: false
    default: 'json'
  masked:
    description: 'Mask variables as secrets.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
