name: Test 

on:
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test action
    steps:
    - uses: actions/checkout@v2
    - name: JSON to variables
      uses: 34ml/json-to-variables@main
      with:
        filename: 'test.json'
    - name: Show output
      run: echo "The time was ${{ env.value }}, ${{ env.array_0_value }}, ${{ env.obj_value1 }}"